(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.PAWSSepsis=api})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
const definitions=[
{key:"cns",name:"CNS",multiple:false,criteria:[["mentation","Altered mentation or deterioration from baseline",1],["mgcs","mGCS ≤14/18 or APPLE mentation score ≥1",2],["delirium","Dysphoria, delirium or other encephalopathic behavior",2],["cranial","New cranial nerve deficit",2],["seizure","New seizure activity",3,true],["coma","Stupor or coma",3,true]]},
{key:"cv",name:"Cardiovascular",multiple:true,criteria:[["crt","Prolonged or rapid capillary refill time",1],["pulses","Weak peripheral pulses",1],["gradient","Increased peripheral-to-core temperature gradient",1],["lactate","Hyperlactatemia >2 mmol/L",1],["acidosis","Persistent unexplained metabolic acidosis; base deficit >6 mmol/L",1],["hypotension","Hypotension after adequate fluid resuscitation",2],["bp_drop","Acute clinically important decrease in blood pressure",2],["persistent_lactate","Persistent hyperlactatemia or inadequate lactate improvement",2],["cardiomyopathy","Sepsis-induced cardiomyopathy",2],["scvo2","ScvO₂ <70% despite adequate fluid resuscitation",3,true],["pressors","New vasopressor or inotrope requirement",3,true],["persistent_hypotension","Persistent hypotension despite adequate fluid resuscitation",3,true]]},
{key:"resp",name:"Respiratory",multiple:false,criteria:[["ards","Mild/moderate ARDSVet",2],["severe_ards","Severe ARDSVet",3,true]]},
{key:"renal",name:"Renal",multiple:false,criteria:[["casts","New urinary casts or other AKI evidence",1],["creatinine","Acute creatinine increase ≥0.3 mg/dL within 48 hours",2],["azotemia","New azotemia consistent with AKI",2],["uop","Urine output <1 mL/kg/hr for ≥6 hours",2],["anuria","Marked oliguria or anuria",3,true],["rrt","New renal replacement therapy requirement",3,true]]},
{key:"hepatic",name:"Hepatic",multiple:true,criteria:[["bilirubin","Hyperbilirubinemia >0.5 mg/dL",2],["ammonia","Hyperammonemia",2],["cholesterol","Hypocholesterolemia",1],["bile_acids","Increased bile acids",1],["adjudicated","Clinician adjudicates severe hepatic dysfunction",3,false]]},
{key:"coag",name:"Coagulation",multiple:true,criteria:[["platelets","Platelets <100 × 10³/µL",2],["platelet_drop","Acute platelet decrease >50%",2],["clotting","New clotting-time prolongation >25% above URL",2],["fibrinogen","Hypofibrinogenemia",2],["ddimer","Increased D-dimer",1],["antithrombin","Decreased antithrombin",1],["protein_c","Decreased protein C",1],["bleeding","New significant bleeding",3,true],["thrombus","New thromboembolic event",3,true],["overt","Overt multicomponent coagulopathy",3,true]]},
{key:"metabolic",name:"Metabolic",multiple:false,criteria:[["glucose","Hypoglycemia",1],["persistent_glucose","Persistent/recurrent hypoglycemia despite treatment",2],["circi","Suspected/diagnosed CIRCI",0],["refractory_circi","CIRCI with refractory cardiovascular dysfunction",3,false]]},
{key:"gi",name:"GI",multiple:true,criteria:[["feeding","Feeding intolerance",1],["ileus","Ileus or marked dysmotility",1],["vomiting","Persistent vomiting",1],["diarrhea","Persistent diarrhea",1],["hematemesis","Hematemesis",2],["hematochezia","Hematochezia",2],["melena","Melena",2],["iah","Intra-abdominal hypertension",2],["adjudicated","Clinician adjudicates severe GI dysfunction",3,false]]}
];
function evaluate(state){const organs={},limitations=[],critical=[];let affected=0,moderate=0,severe=0;
for(const d of definitions){const selected=state.organs?.[d.key]||[],scores=d.criteria.filter(c=>selected.includes(c[0])).map(c=>c[2]);let sev=scores.length?Math.max(...scores):0;if(d.multiple&&scores.filter(x=>x===1).length>=2)sev=Math.max(sev,2);let excluded=!!state.excluded?.[d.key];if(d.key==="cv"&&!state.resuscitated&&selected.length){excluded=true;limitations.push("Cardiovascular findings not counted: adequate resuscitation/hypovolemia correction not confirmed")}if(excluded&&selected.length)limitations.push(d.name+" excluded from counts");const observed=sev;if(excluded)sev=0;if(sev>=1)affected++;if(sev>=2)moderate++;if(sev===3)severe++;d.criteria.forEach(c=>{if(!excluded&&selected.includes(c[0])&&c[2]===3&&c[3]!==false)critical.push(d.name+": "+c[1])});organs[d.key]={name:d.name,severity:sev,observed,selected,excluded}}
let overall;if(critical.length)overall=affected>1?"Critical multisystem organ dysfunction":"Critical organ dysfunction";else if(!affected)overall="No identified organ dysfunction";else if(severe||moderate>=2||(affected>=3&&moderate>=1))overall=affected>1?"Severe multisystem organ dysfunction":"Severe organ dysfunction";else if(moderate||affected>=2)overall=affected>1?"Moderate multisystem organ dysfunction":"Moderate organ dysfunction";else overall="Limited organ dysfunction";
const classification=!state.infection?"Sepsis criteria not met — no known or suspected infection documented.":affected?"Sepsis criteria potentially met":"Known/suspected infection without identified sepsis-associated organ dysfunction";
let shock="Not suspected by this screen";if(state.adjudicatedShock)shock="Present — clinician-adjudicated septic shock";else if(state.infection&&state.resuscitated&&organs.cv.severity&&["persistent_hypotension","pressors","scvo2","persistent_lactate","acidosis","hypotension","bp_drop"].some(k=>organs.cv.selected.includes(k)))shock="Concern present — High; clinician adjudication recommended";
const names=Object.values(organs).filter(o=>o.selected.length).map(o=>o.name+": "+["None","Mild","Moderate","Severe"][o.observed]+(o.excluded?" — excluded":""));
const text=[`Sepsis assessment: ${overall}`,classification,`Organs: ${affected} affected; ${moderate} moderate/severe; ${severe} severe.`,names.join("; "),`Critical (${critical.length}): ${critical.length?critical.join("; "):"None identified"}`,`Septic shock: ${shock}`,limitations.length?"Limitations: "+limitations.join("; "):""].filter(Boolean).join("\n");
return{organs,affected,moderate,severe,critical,overall,classification,shock,limitations,text}}
return Object.freeze({definitions,evaluate})});